In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
%matplotlib tk

In [2]:
# Define the objective function to be minimized
def objective(x):
    return 5 * x[0] - 3 * x[1]

In [3]:
# Define the constraint function
def constraint(x):
    return x[0] + x[1] - 5

In [4]:
# Define the Lagrangian function
def lagrangian(x, lmd):
    return objective(x) + lmd * constraint(x)

In [5]:
# Define the partial derivatives of the Lagrangian function
def lagrangian_partial(x, lmd):
    dL_dx0 = 5 + lmd
    dL_dx1 = -3 + lmd
    dL_dlmd = constraint(x)
    return np.array([dL_dx0, dL_dx1, dL_dlmd])

In [ ]:
# Define the initial guess for the variables and the Lagrange multiplier
x0 = np.array([1, 1])
lmd0 = 0

In [8]:
# Define the maximum number of iterations and the tolerance for the optimization algorithm
max_iter = 100
tol = 1e-6

In [9]:
# Initialize the iteration counter and the difference between the previous and current Lagrange multiplier values
iter_count = 0
lmd_diff = 1

In [10]:
# Iterate until the Lagrange multiplier converges or the maximum number of iterations is reached
while lmd_diff > tol and iter_count < max_iter:
    # Calculate the partial derivatives of the Lagrangian function with respect to the variables and the Lagrange multiplier
    partials = lagrangian_partial(x0, lmd0)
    print(partials)
    # Calculate the update to the variables and the Lagrange multiplier using the partial derivatives
    x_update = x0 - 0.1 * partials[:-1]
    lmd_update = lmd0 + 0.1 * partials[-1]
    
    # Calculate the difference between the previous and current Lagrange multiplier values
    lmd_diff = abs(lmd_update - lmd0)
    
    # Update the variables and the Lagrange multiplier
    x0 = x_update
    lmd0 = lmd_update
    print(x0)
    # Increment the iteration counter
    iter_count += 1

[ 5 -3 -3]
[0.5 1.3]
[ 4.7 -3.3 -3.2]
[0.03 1.63]
[ 4.38 -3.62 -3.34]
[-0.408  1.992]
[ 4.046 -3.954 -3.416]
[-0.8126  2.3874]
[ 3.7044 -4.2956 -3.4252]
[-1.18304  2.81696]
[ 3.36188 -4.63812 -3.36608]
[-1.519228  3.280772]
[ 3.025272 -4.974728 -3.238456]
[-1.8217552  3.7782448]
[ 2.7014264 -5.2985736 -3.0435104]
[-2.09189784  4.30810216]
[ 2.39707536 -5.60292464 -2.78379568]
[-2.33160538  4.86839462]
[ 2.11869579 -5.88130421 -2.46321075]
[-2.54347496  5.45652504]
[ 1.87237472 -6.12762528 -2.08694991]
[-2.73071243  6.06928757]
[ 1.66367973 -6.33632027 -1.66142485]
[-2.8970804  6.7029196]
[ 1.49753724 -6.50246276 -1.1941608 ]
[-3.04683412  7.35316588]
[ 1.37812116 -6.62187884 -0.69366825]
[-3.18464624  8.01535376]
[ 1.30875434 -6.69124566 -0.16929248]
[-3.31552167  8.68447833]
[ 1.29182509 -6.70817491  0.36895665]
[-3.44470418  9.35529582]
[ 1.32872075 -6.67127925  0.91059164]
[-3.57757626 10.02242374]
[ 1.41977992 -6.58022008  1.44484749]
[-3.71955425 10.68044575]
[ 1.56426467 -6.43573

In [11]:
# Print the optimal values of the variables and the Lagrange multiplier
print("Optimal values of the variables:", x0)
print("Optimal value of the Lagrange multiplier:", lmd0)

Optimal values of the variables: [-39.75146518  40.24853482]
Optimal value of the Lagrange multiplier: -6.450446103299718


In [12]:
cost_social = 2500
cost_tv = 25000
budget = 2500000

In [13]:
social_min = 0
social_max = budget / cost_social

tv_min = 0
tv_max = budget / cost_tv

In [14]:
def n_social(n_tv, budget):
    return (budget - 25000 * n_tv) / 2500

In [15]:
def n_tv(n_social, budget):
    return (budget - 2500 * n_social) / 25000

In [16]:
social_x = np.linspace(social_min, social_max, 100)
tv_y = n_tv(social_x, budget)

plt.figure(figsize=(10,5))
plt.plot(social_x, tv_y)
plt.xlabel('Number of social campaigns')
plt.ylabel('Number of tv campaigns')
plt.title('Possible ways of spending the budget')
plt.show()

In [17]:
def revenues(social, tv):
    return social**(3/4) * tv**(1/4) * 7

In [20]:
from mpl_toolkits.mplot3d import Axes3D
social_axis = np.linspace(social_min, social_max, 100)
tv_axis = np.linspace(tv_min, tv_max, 100)
social_grid, tv_grid = np.meshgrid(social_axis, tv_axis)

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

ax.plot_surface(tv_grid, social_grid, revenues(social_grid, tv_grid))

ax.plot(tv_y, social_x, linewidth = 5, color = 'r')

ax.set_xlabel('Number of hours bought')
ax.set_ylabel('Number of materials bought')
ax.set_title('Possible ways of spending the budget')
plt.show()

In [33]:
fig, (ax_l, ax_r) = plt.subplots(1, 2, figsize = (15, 5))


social_axis = np.linspace(social_min, social_max, 100)
tv_axis = np.linspace(tv_max, tv_min, 100)
social_grid, tv_grid = np.meshgrid(social_axis, tv_axis)
    
im = ax_l.imshow(revenues(social_grid, tv_grid), aspect = 'auto', extent=[social_min, social_max, tv_min, tv_max])
ax_l.plot(social_axis, n_tv(social_axis, 2500000), 'r')
ax_l.set_xlabel('Number of social campaigns bought')
ax_l.set_ylabel('Number of tv campaigns bought')
ax_l.set_title('Possible ways of spending the budget')


# The contours are showing how the intersection looks like

social_axis = np.linspace(social_min, social_max)
tv_axis = np.linspace(tv_min, tv_max)
social_grid, tv_grid = np.meshgrid(social_axis, tv_axis)

im2 = ax_r.contour(revenues(social_grid,tv_grid), extent=[social_min, social_max, tv_min, tv_max])
ax_r.plot(social_axis, n_tv(social_axis, 2500000), 'r')
ax_r.set_xlabel('Number of social campaings bought')
ax_r.set_ylabel('Number of tv campaigns bought')
ax_r.set_title('Possible ways of spending the budget')

plt.colorbar(im,ax=ax_l)
plt.colorbar(im2,ax=ax_r)

plt.show()

In [29]:
from sympy import *

s, t, l = symbols('s t l')

solve([Eq((21/4)*((t**(1/4))/s**(1/4)) - 2500*l, 0),
   Eq((7/4)*(s**(3/4)/t**(3/4)) - 25000*l, 0),
   Eq(2500*s+25000*t - 2500000, 0)], [s,t,l], simplify=False)

[(750.000000000000, 25.0000000000000, 0.000897302713432092)]

In [32]:
revenues(750, 25)

2243.256783580229

In [34]:
# Define the objective function to be minimized
def objective(x):
    return x[0]**2 + x[1]**2

In [35]:
# Define the constraint function
def constraint(x):
    return x[0] + x[1] - 5

In [37]:
# Define the Lagrangian function
def lagrangian(x, lmd):
    return objective(x) + lmd * constraint(x)

In [38]:
# Define the partial derivatives of the Lagrangian function
def lagrangian_partial(x, lmd):
    dL_dx0 = 2 * x[0] + lmd
    dL_dx1 = 2 * x[1] + lmd
    dL_dlmd = constraint(x)
    return np.array([dL_dx0, dL_dx1, dL_dlmd])

In [39]:
# Define the initial guess for the variables and the Lagrange multiplier
x0 = np.array([1, 1])
lmd0 = 0

In [40]:
# Define the maximum number of iterations and the tolerance for the optimization algorithm
max_iter = 100
tol = 1e-6

In [41]:
# Create a figure and axis for the animation
fig, ax = plt.subplots(figsize=(8, 6))

# Define the x and y limits for the plot
ax.set_xlim(-1, 6)
ax.set_ylim(-1, 6)
# Define the x and y values for the constraint line
x_constraint = np.linspace(0, 5, 100)
y_constraint = 5 - x_constraint
# Plot the constraint line
ax.plot(x_constraint, y_constraint, 'k--')
# Define a scatter plot for the iterations of the optimization algorithm
scatter = ax.scatter([], [])
# Initialize the iteration counter and the difference between the previous and current Lagrange multiplier values
iter_count = 0
lmd_diff = 1
# Define a function to update the scatter plot for each iteration of the optimization algorithm
def update_plot(i):
    global x0, lmd0, iter_count, lmd_diff

    # Calculate the partial derivatives of the Lagrangian function with respect to the variables and the Lagrange multiplier
    partials = lagrangian_partial(x0, lmd0)

    # Calculate the update to the variables and the Lagrange multiplier using the partial derivatives
    x_update = x0 - 0.1 * partials[:-1]
    lmd_update = lmd0 + 0.1 * partials[-1]

    # Calculate the difference between the previous and current Lagrange multiplier values
    lmd_diff = abs(lmd_update - lmd0)

    # Update the variables and the Lagrange multiplier
    x0 = x_update
    lmd0 = lmd_update

    # Increment the iteration counter
    iter_count += 1

    # Update the scatter plot with the current values of the variables
    scatter.set_offsets(x0)

    # Return the scatter plot for the current iteration
    return scatter,
# Create an animation of the optimization algorithm
animation = animation.FuncAnimation(fig, update_plot, frames=max_iter, blit=True)

# Show the animation
plt.show()